# Generated by Django 2.0.3 on 2018-04-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowlegeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
            ],
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.KnowlegeField'),
        ),
    ]
