# Generated by Django 2.0.3 on 2018-04-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20180405_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Процесс', 'verbose_name_plural': 'Процессы'},
        ),
    ]
