# Generated by Django 2.0.3 on 2018-04-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20180405_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowlegefield',
            options={'verbose_name': 'Область знаний', 'verbose_name_plural': 'Области знаний'},
        ),
        migrations.AlterModelOptions(
            name='processgroup',
            options={'verbose_name': 'Группа процессов', 'verbose_name_plural': 'Группы процессов'},
        ),
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
