# Generated by Django 2.0.3 on 2018-04-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, unique=True, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Краткое название')),
            ],
        ),
    ]
