# Generated by Django 2.0.3 on 2018-04-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['short_name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
